// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB46uUxVfdf5ec0vbtNwMhliQRoWkyFIfo',
    appId: '1:146599908794:web:134e7c6b061939f39cf983',
    messagingSenderId: '146599908794',
    projectId: 'smart-tourism-guide-9abbe',
    authDomain: 'smart-tourism-guide-9abbe.firebaseapp.com',
    storageBucket: 'smart-tourism-guide-9abbe.firebasestorage.app',
    measurementId: 'G-VCERKXP8PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhNu2PvnlAa4A9aNC5_-CQ_h23vdwG5sc',
    appId: '1:146599908794:android:97ed39a61f49ea6f9cf983',
    messagingSenderId: '146599908794',
    projectId: 'smart-tourism-guide-9abbe',
    storageBucket: 'smart-tourism-guide-9abbe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC6WknOhP9u3c6p5Td1P8YR-SsSXmMqee8',
    appId: '1:146599908794:ios:b2e87765ee496bb39cf983',
    messagingSenderId: '146599908794',
    projectId: 'smart-tourism-guide-9abbe',
    storageBucket: 'smart-tourism-guide-9abbe.firebasestorage.app',
    iosBundleId: 'com.example.smartTourismGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC6WknOhP9u3c6p5Td1P8YR-SsSXmMqee8',
    appId: '1:146599908794:ios:b2e87765ee496bb39cf983',
    messagingSenderId: '146599908794',
    projectId: 'smart-tourism-guide-9abbe',
    storageBucket: 'smart-tourism-guide-9abbe.firebasestorage.app',
    iosBundleId: 'com.example.smartTourismGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB46uUxVfdf5ec0vbtNwMhliQRoWkyFIfo',
    appId: '1:146599908794:web:11788c6f873f2ba09cf983',
    messagingSenderId: '146599908794',
    projectId: 'smart-tourism-guide-9abbe',
    authDomain: 'smart-tourism-guide-9abbe.firebaseapp.com',
    storageBucket: 'smart-tourism-guide-9abbe.firebasestorage.app',
    measurementId: 'G-DY25786K71',
  );
}
